In [4]:

import numpy as np

a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b) 

0

In [7]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
Z

array([[1, 1],
       [1, 1]])

In [8]:

X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3]
out

array([0, 1])

In [10]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)

In [11]:
Z

array([[2, 2],
       [2, 2]])